apiVersion: v2
name: backend
description: A Helm chart for Kubernetes

type: application

version: 0.0.1

dependencies:
  - name: redis
    version: 17.2.0
    repository: https://charts.bitnami.com/bitnami
  - name: couchbase-operator
    version: 2.32.0
    repository: https://couchbase-partners.github.io/helm-charts/
