on:
   push:
     branches:
       - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      frontend-release: ${{ steps.release.outputs.frontend--release_created }}
      frontend-tag: ${{ steps.release.outputs.frontend--tag_name }}
      backend-tag: ${{ steps.release.outputs.backend--tag_name }}
      backend-release: ${{ steps.release.outputs.backend--release_created }}
      core-release: ${{ steps.release.outputs.releases_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          command: manifest
  build-frontend:
    runs-on: ubuntu-latest    
    needs: release-please
    if: ${{ needs.release-please.outputs.frontend-release }}
    steps:
      - run: echo docker push ${{ needs.release-please.outputs.frontend-tag }}
  build-backend:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.backend-release }}
    steps:
      - run: echo docker push ${{ needs.release-please.outputs.backend-tag }}
  deploy-helm:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    if: always() && needs.release-please.outputs.core-release
    steps:
      - run: echo helm upgrade tim
